In [2]:
# content based recommendation engine

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import scipy as sp

In [3]:
cv = CountVectorizer()
text = ["how are you","how are you girl"]
count_matrix = cv.fit_transform(text)
print(cv.get_feature_names())
print(count_matrix.toarray())

['are', 'girl', 'how', 'you']
[[1 0 1 1]
 [1 1 1 1]]


In [4]:
similarity = cosine_similarity(count_matrix)
print(similarity)

[[1.        0.8660254]
 [0.8660254 1.       ]]


In [5]:
df = pd.read_csv("C:/Users/admin/Downloads/chennai-zomato-restaurants-data/Chennai_Zomato_Data_updated.csv")
print(df.head())

   Unnamed: 0                                         Zomato URL  \
0           0  https://www.zomato.com/chennai/the-big-barbequ...   
1           1  https://www.zomato.com/chennai/abs-absolute-ba...   
2           2  https://www.zomato.com/chennai/mcdonalds-velac...   
3           3  https://www.zomato.com/chennai/sukkubhai-biriy...   
4           4  https://www.zomato.com/chennai/coal-barbecues-...   

          Name of Restaurant  \
0           The Big Barbeque   
1  AB's - Absolute Barbecues   
2                 McDonald's   
3         Sukkubhai Biriyani   
4             Coal Barbecues   

                                             Address  \
0   5/360, Okkiyum Thoraipakkam Rajiv Gandhi Sala...   
1              45, GN Chetty Road, T. Nagar, Chennai   
2   330/12, Grand Arcade, Dr Seetharaman Nagar, V...   
3   New 14, Old 11/3Q, Railway Station Road, MKN ...   
4    40, 2nd Floor, Bazullah Road, T. Nagar, Chennai   

                       Location  \
0  Old Mahabalipuram Road 

In [6]:
print(df["Cuisine"].head(6))

0             North Indian, Street Food, Desserts, BBQ
1                          BBQ, North Indian, European
2                                    Burger, Fast Food
3    Biryani, North Indian, Mughlai, Desserts, Beve...
4                                North Indian, Chinese
5                                              Biryani
Name: Cuisine, dtype: object


In [7]:
print(df[["Cuisine","Ratings"]].head())

                                             Cuisine  Ratings
0           North Indian, Street Food, Desserts, BBQ  invalid
1                        BBQ, North Indian, European      4.8
2                                  Burger, Fast Food      3.9
3  Biryani, North Indian, Mughlai, Desserts, Beve...      4.4
4                              North Indian, Chinese      4.9


In [8]:
print(df.columns);

Index(['Unnamed: 0', 'Zomato URL', 'Name of Restaurant', 'Address', 'Location',
       'Cuisine', 'Top Dishes', 'Price for 2', 'Ratings', 'No of Votes'],
      dtype='object')


In [10]:
c = list(df.columns)
total = len(c)

In [11]:
df.replace(to_replace=["invalid","Invalid",","],value=" ")
def combines(row): 
    return row["Name of Restaurant"]+" "+row['Address']+" " + row["Location"]+" "+ str(row['Price for 2'])+" "+str(row['Ratings'])+" "+str(row['No of Votes'])+" "+row['Zomato URL']+" "+row['Cuisine']+" "+row['Top Dishes']
#     return row['Unnamed: 0']+" "+row['Zomato URL']+" "+row['Name of Restaurant']+" "+row['Address']+" "+row['Location']+" "+row['Cuisine']+" "+row['Top Dishes']+" "+row['Price for 2']+" "+row['Ratings']+" "+row['No of Votes']

In [12]:
df["combined"] = df.apply(combines,axis=1)
dv = CountVectorizer()
count_mat = dv.fit_transform(df["combined"])
cosine_similarty = cosine_similarity(count_mat)

In [26]:
def get_title_from_index(index):
    return df[df.index==index]["Name of Restaurant"].values[0]

def get_index_from_title(title):
    return df[df["Name of Restaurant"]==title].index[0]

In [29]:
hotel = "McDonald's"
hotel_index = get_index_from_title(hotel)
similar_hotels = list(enumerate(cosine_similarty[hotel_index]))
sorted_hotels = sorted(similar_hotels,key=lambda x:x[1],reverse=True)[1:]
i=0
# print(“Top 5 similar hotels to are:\n”)
for element in sorted_hotels:
    print(get_title_from_index(element[0]))
    i=i+1
    if i>5:
        break

Galito's
Gharwaalatiffin
7th Heaven
Willows
Burger House
Burger House


In [36]:
print(df[df["Name of Restaurant"]=="Gharwaalatiffin"])

      Unnamed: 0                                         Zomato URL  \
2915        2915           https://www.zomato.com/gharwaalatiffin-1   
4538        4538  https://www.zomato.com/chennai/gharwaalatiffin...   

     Name of Restaurant                                        Address  \
2915    Gharwaalatiffin                                  Delivery Only   
4538    Gharwaalatiffin   137, Velachery Main Road, Velachery, Chennai   

          Location                                      Cuisine Top Dishes  \
2915  Nungambakkam             Fast Food, North Indian, Chinese    Invalid   
4538     Velachery  Biryani, North Indian, Chinese, Street Food    Invalid   

      Price for 2 Ratings No of Votes  \
2915        500.0     3.3          32   
4538        500.0     2.7           9   

                                               combined  
2915  Gharwaalatiffin  Delivery Only Nungambakkam 50...  
4538  Gharwaalatiffin  137, Velachery Main Road, Vel...  
